#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEngine;

namespace Ezg.Feature.LocalNotification.EditorTools
{
    /// <summary>
    ///     Scaffolding helper for the Local Notification package. Generates a project-side
    ///     <c>LocalNotificationScriptInfo.cs</c> template that developers fill in with their own
    ///     notification rules. The generated file intentionally stays OUT of the package: it is the
    ///     bridge between the generic engine and game-specific scheduling logic.
    /// </summary>
    public static class LocalNotificationSetupMenu
    {
        #region Fields

        private const string MENU_PATH = "Assets/Create/Ezg/Local Notification/Project setup";
        private const string TARGET_FILE_NAME = "LocalNotificationScriptInfo.cs";
        private const string FALLBACK_MODULE_DIR = "Assets/_Project/Features/_Shared/LocalNotification";

        #endregion

        #region Private Methods

        [MenuItem(MENU_PATH, priority = 80)]
        private static void CreateProjectSetup()
        {
            var moduleDir = ResolveModuleDir();
            var targetPath = $"{moduleDir}/{TARGET_FILE_NAME}";

            if (File.Exists(targetPath))
            {
                var overwrite = EditorUtility.DisplayDialog(
                    "Local Notification — Project setup",
                    $"'{TARGET_FILE_NAME}' already exists at:\n{moduleDir}\n\n" +
                    "Overwrite it with a fresh template? Your current implementation in this file will be lost.",
                    "Overwrite",
                    "Cancel");

                if (!overwrite)
                {
                    Debug.Log("[LocalNotification] Project setup cancelled. Existing template kept.");
                    return;
                }
            }
            else if (!Directory.Exists(moduleDir))
            {
                Directory.CreateDirectory(moduleDir);
            }

            File.WriteAllText(targetPath, BuildTemplate());
            AssetDatabase.ImportAsset(targetPath, ImportAssetOptions.ForceUpdate);
            AssetDatabase.Refresh();

            var created = AssetDatabase.LoadAssetAtPath<Object>(targetPath);
            if (created != null)
            {
                Selection.activeObject = created;
                EditorGUIUtility.PingObject(created);
            }

            Debug.Log($"[LocalNotification] Project setup template written to {targetPath}.");
        }

        /// <summary>
        ///     Resolves the module folder relative to this editor script so the template is dropped
        ///     next to the package wherever it is installed. Falls back to the canonical project path.
        /// </summary>
        private static string ResolveModuleDir()
        {
            var guids = AssetDatabase.FindAssets($"{nameof(LocalNotificationSetupMenu)} t:MonoScript");
            for (int index = 0; index < guids.Length; index++)
            {
                var scriptPath = AssetDatabase.GUIDToAssetPath(guids[index]);
                if (!scriptPath.EndsWith($"{nameof(LocalNotificationSetupMenu)}.cs"))
                {
                    continue;
                }

                var editorDir = Path.GetDirectoryName(scriptPath); // <module>/Editor
                var moduleDir = Path.GetDirectoryName(editorDir);  // <module>
                if (!string.IsNullOrEmpty(moduleDir))
                {
                    return moduleDir.Replace('\\', '/');
                }
            }

            return FALLBACK_MODULE_DIR;
        }

        /// <summary>
        ///     The template body written to disk. Mirrors the decoupled wiring pattern: the project
        ///     subscribes its rules to <see cref="LocalNotificationService.AppPaused"/> at startup.
        /// </summary>
        private static string BuildTemplate()
        {
            return
@"using System;
using UnityEngine;

namespace Ezg.Feature.LocalNotification
{
    // =====================================================================
    //  PROJECT TEMPLATE — generated by:
    //      Create > Ezg > Local Notification > Project setup
    //
    //  This file lives in YOUR PROJECT, not inside the LocalNotification
    //  package. It is the bridge between the generic notification engine and
    //  your game-specific scheduling rules. Implement your own logic here.
    // =====================================================================

    /// <summary>Sample metadata holder for a single notification script entry.</summary>
    public sealed class LocalNotificationScriptInfo
    {
        public string Id;
        public string TitleKey;
        public string ContentKey;
        // TODO: [You] - add the fields your project needs (action, trigger condition, ...).
    }

    /// <summary>
    ///     Project-side scheduling rules. The package raises hooks; this class subscribes to them
    ///     so the package never has to reference your game code.
    /// </summary>
    public static class LocalNotificationRules
    {
        // Wire project rules into the package's app-paused hook at startup.
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        private static void RegisterHooks()
        {
            LocalNotificationService.AppPaused -= RegisterPauseNotifications;
            LocalNotificationService.AppPaused += RegisterPauseNotifications;
        }

        /// <summary>
        ///     Invoked every time the app is sent to the background. Register (or refresh) every
        ///     notification you want delivered while the player is away.
        /// </summary>
        public static void RegisterPauseNotifications()
        {
            // TODO: [You] - register your real notifications here.
            RegisterSampleReminder();
        }

        // ---- Sample rule. Delete once you add your own. ---------------------
        private static void RegisterSampleReminder()
        {
            const string id = ""SAMPLE_001"";
            const long oneHourSeconds = 60 * 60;

            LocalNotificationService.RegisterOrReplace(
                id,
                new NotificationDefinition(id)
                    .WithContent(new NotificationContentTemplate()
                        .WithTitleText(""We miss you!"")
                        .WithBodyText(""Tap to jump back into the game.""))
                    .WithSchedule(() => NotificationScheduleRequest.CreateDelay(oneHourSeconds)));
        }
    }
}
";
        }

        #endregion
    }
}
#endif
